config/routes.rb
Qd::Application.routes.draw do
  root to: 'home#index'

  resource :search, only: [:create, :new], controller: 'search', defaults: {format: :json}

  resources :parties, only: [:create, :show, :new, :index]
  get '/party/join', to: 'parties#join'
  get '/party/search', to: 'parties#search'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :url

  validates_uniqueness_of :password
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :parties

  def self.find_or_create_from_auth_hash(auth_hash)
    user = self.find_or_create_by(rdio_uid: auth_hash["uid"])
    if user
      first_name = auth_hash["info"]["first_name"]
      last_name = auth_hash["info"]["last_name"]
      profile_pic_url = auth_hash["info"]["image"]
      user.update_attributes(first_name: first_name, last_name: last_name, profile_pic_url: profile_pic_url)
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :signed_in?, :current_user, :body_class, :render_toggle

  private

  def body_class
    if request.path == '/' or request.path == '/party/join'
      'home'
    else
      ""
    end
  end

  def render_toggle
    request.path != '/' and request.path != '/parties/new' and request.path != '/party/join'
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@party = Party.new(password: "From Hipster Ipsum")
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  include PasswordHelper

  def create
    @party = Party.new
    until @party.save
      @party.user_id = current_user.id
      @party.url = SecureRandom.urlsafe_base64
      @party.password = generatePassword
    end
    redirect_to party_path(@party.url)
  end

  def show
    @party = Party.find_by_url(params[:id])
  end

  def new
    @parties = Party.find_all_by_user_id(current_user.id)
  end

  def join
  end

  def search
    @party = Party.find_by_password(params[:password].split(' ').map { |word| word.capitalize }.join(' '))
    if @party
      redirect_to party_path(@party.url)
    else
      redirect_to :back
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include Rdio
  def create
    response = Rdio.query(params[:song])
    json = response.to_json
    render :json => json
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to new_party_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_helper.rb
module PasswordHelper
  def generatePassword
    page = Nokogiri::HTML(open("http://hipsteripsum.me/?paras=1&type=hipster-centric"))
    page_string = page.css("div[id='content']").css("p")[0].content
    words_string = page_string.sub(/[<].{1,2}[>]/,"").gsub(/[^a-zA-Z ]/, "")
    words_array = words_string.split(" ").delete_if{ |word| word.length < 5 }.map{|word| word.capitalize }
    return "#{words_array.sample} #{words_array.sample}"
  end
end

app/helpers/rdio.rb
module Rdio
  # usage: Rdio.query("song you want")
  extend self

  def new
    consumer = OAuth::Consumer.new(ENV['RDIO_CONSUMER_KEY'], ENV['RDIO_CONSUMER_SECRET'], {
      :site   => 'http://api.rdio.com',
      :scheme => :header
      })
  end
  def query(song)
    consumer = self.new
    song = URI.encode(song)
    resp = consumer.request(:post, '/1/search', nil, {}, "method=search&query=#{song}&types=tracks&count=25", { 'Content-Type' => 'application/x-www-form-urlencoded' })
    resp.body
  end
end

if $0 == __FILE__
  puts "Creating Oauth signature.."
  search_term = ARGV.join(" ")
  puts "Querying Rdio with #{search_term}... "
  puts ""
  result =  Rdio.query(search_term)
  puts result
end

app/views/home/_player.html.erb
<div class="player", id="player">
  <div id="rdio-player"></div>

  <!-- when expanded -->
  <div class="player-expanded-view">
    <div class="single-track expanded">
      <img class="current-song-album-art">
      <div class="current-song-info">
        <span class="current-song-track"></span>
        <span class="current-song-album"></span>
        <span class="current-song-artist"></span>
        </div>
    </div>

    <div class='queue-container'>
      <!-- actual top container -->
      <ul class='queue-track-info queue-top-list'></ul>
    </div>
  </div>

  <!-- player controls -->
  <div id="controls">
    <i class="icon-pause icon-large" id="pause"></i>
    <i class="icon-play icon-large" id="play"></i>
    <i class="icon-forward icon-large" id="next"></i>
  </div>
  <div id="player-center">
    <div id="song-info">
      <span class="current-song-track">Song </span> -- <span class="current-song-artist"> Artist</span>
    </div>

      <div id="progress-bar"><div></div></div>
      <span id="position"> Position yo! </span>

  </div>
  <div id="album-art-container">
    <%= image_tag("http://rdio-b.cdn3.rdio.com/album/8/2/5/0000000000019528/2/square-200.jpg", id: 'art') %>
    <i class="fa fa-align-justify"></i>
  </div>


</div>

<div class="player background", id="player-background">
</div>

app/views/home/_search_container.html.erb
<div class='pure-g-r'>

    <!-- main queue placeholder -->

    <!-- mock main queue -->
<!--     <div class='queue-container main'>
      <ul class="queue-track-info queue-list">
        <% 5.times do %>
            <li>

              <span> 8 </span>
              <img src="http://rdio-b.cdn3.rdio.com/album/8/2/5/0000000000019528/2/square-200.jpg" class="front-page-art">
              <div class ="queue-span-wrapper">Track Name</div>
              <div class ="queue-span-wrapper">Artist Name</div>
              <div class ="queue-span-wrapper icon"><i class="icon-thumbs-up icon-large"></i></div>
            </li>
          <hr class="queue-border"></hr>
        <% end %>
      </ul>
    </div> -->


    <!-- actual main queue  -->
   <div class='queue-container main'>
      <ul class='queue-track-info queue-list'></ul>
   </div>


  <!-- search results  -->
  <div class="search-container pure-g-r">
    <form class='search-form'>
        <input class='search-input-term' placeholder="Search for a song" id='search-input-term'>
        <button class='pure-button search-submit' >Search</button>
    </form>

    <!-- actual search -->
    <div class='results-container pure-g-r'></div>




    <!-- new search look mock -->
    <!-- <div class='results-container pure-g-r'>
      <% 10.times do %>
      <div class="pure-u-1-8 single-track result">
        <div class="album-art-container">

          <img src="/assets/overlay-click-200.png" class="overlay">
          <img src="http://rdio-d.cdn3.rdio.com/album/f/9/8/000000000001f89f/square-200.jpg" class="front-page-art result-album-art">
        </div>
        <div class="result-song-details">
          <span class="result-artist">The Beatlessdfsdfsd</span>
          <span class="result-song">Twist And Shoutfdsfsdfsd</span>
          <span class="result-album">20 Mejores Canciones de Briti</span>
        </div>
      </div>
      <% end %>
    </div> -->

  </div>


</div>

app/views/home/index.html.erb
<div class="landing-page-logo-container">
  <img src="<%= asset_path('qd-home-logo.png') %>">
  <p> Crowdsource your party playlist </p>
</div>
<div class="container">
  <div class="home-buttons-container">
    <% if current_user %>
      <%= link_to 'Host Party', new_party_path, method: 'get', class: "pure-button button-large" %>
    <% else %>
      <%= link_to 'Sign-In with rdio', '/auth/rdio', class: "pure-button button-large" %>
    <% end %>
    <%= link_to 'Join a party', party_join_path, class: "pure-button button-large" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal", id="navbar">
     <a href="/"><img src="<%= asset_path('qd-small-logo.png') %>" class="pure-menu-heading" id="logo"></a>
     <% if render_toggle %>
        <div class="toggle-switch">
          <label class="switch-light switch-candy">
            <input type="checkbox">
            <span >
              <span id="search-toggle"><i class="icon-search icon-large"></i></span>
              <span id="queue-toggle"><i class="icon-reorder"></i></span>
            </span>
            <a class="pos"></a>
          </label>
        </div>
    <% end %>

      <% if signed_in? %>
        <!-- render toggle with no margin when signed in  -->
        <% if render_toggle %>
          <ul >
        <% else %>
          <ul class="no-margin">
        <% end %>
            <li><%= image_tag(current_user.profile_pic_url, id: 'profile-image') %></li>
            <li> <%= link_to 'Log out', logout_path, method: :get, class: 'pure-button',  id: 'logout-button' %></li>
          </ul>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qd</title>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script type='text/javascript' src='https://cdn.firebase.com/v0/firebase.js'></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= csrf_meta_tags %>

  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-45123275-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>

</head>
<body class="<%= body_class %>">


<%= render 'layouts/header' %>


  <%= yield %>
</body>
</html>

app/views/parties/_bottom_player.html.erb
<div class="pure-menu pure-menu-open pure-menu-horizontal", id="player">
  <div id="rdio-player"></div>
  <div id="controls">
    <i class="icon-backward icon-large" id="pause"></i>
    <i class="icon-play icon-large" id="play"></i>
    <i class="icon-forward icon-large" id="next"></i>
  </div>

  <div id="player-center">
    <div id="song-info">
      <span id="track"> Song </span> -- <span id="artist"> Artist</span>
    </div>
    <div >
      <span id="position"> Position yo! </span>
    </div>
  </div>
  <div id="album-art-container">
    <%= image_tag("http://rdio-b.cdn3.rdio.com/album/8/2/5/0000000000019528/2/square-200.jpg", id: 'art') %>
  </div>
</div>

<div class="pure-menu pure-menu-open pure-menu-horizontal", id="player-background">

</div>

app/views/parties/_parties_list.html.erb
<% if !@parties.empty? %>

  <div class='old-parties-container'>
  <hr class="queue-border"></hr>
    <span >...or shake the dust off of one of these old parties:</span>
    <ul>
      <% @parties.each do |party| %>
        <li class="old-parties"><%= link_to party.password, party_path(party.url), action: 'get' %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/parties/_rotate.html.erb
<div class="hover panel">
    <div class="front">
            <button class='rotate' style="width: 200px"> Rotate </button>
        <div class="pad">
        </div>
    </div>
    <div class="back">
        <div class="pad">
            <form action="post">
                First name: <input type="text" name="firstname"><br>
                Last name: <input type="text" name="lastname"><br>
            </form>
        </div>
    </div>
</div>

app/views/parties/join.html.erb
<div class="container">
  <div class="join-party-form-container">
  <%= form_tag('/party/search/', :method => :get) do %>
    <div><%= label_tag(:password, "Enter Room Name") %></div>
    <div><%= text_field_tag(:password) %></div>
    <div><%= submit_tag("Let's Do This!", class: "pure-button join-party") %></div>
  <% end %>
  </div>
</div>

app/views/parties/new.html.erb
<div class="container">
  <div class="home-buttons-container">
    <%= button_to 'Create Party!', parties_path, class: 'pure-button button-large new-party', method: :post %>
  </div>
    <%= render 'parties_list' %>
</div>

app/views/parties/show.html.erb
<div class='container'>

  <div class="party-name">
    <p><%= @party.password %><p>
  </div>

  <%= render 'home/search_container' %>
  <% if current_user && @party.user_id == current_user.id %>
    <%= render 'home/player' %>
  <% end %>



  </div>
</div>